---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-java-maven-basic-test
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[push]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the reference CNAP pipeline
    pipelinesascode.tekton.dev/pipeline: "https://github.com/KMD-A-S-CNAP/pipelines-tasks/blob/main/pipelines-pac/ci-java-maven-basic/0.3/ci-java-maven-basic.yaml"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task-3: "https://github.com/KMD-A-S-CNAP/pipelines-tasks/blob/main/tasks/set-results-from-cm/0.3/set-results-from-cm.yaml"
    # how many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineRef:
    name: pipeline-1
    params:
      - name: repo_url
      - name: revision
      - name: repo_owner
      - name: repo_name
    workspaces:
      - name: source
      - name: maven-settings
  workspaces:
    - name: dockerconfig
      secret:
        secretName: kaniko-quay-secret
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - configMap:
        name: maven-settings
      name: maven-settings
